# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mymessage', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
